platform :ios, '12.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  
  # Specify the Swift version based on your screenshot
  # Adjust the SWIFT_VERSION to match Swift 5.5 as it is listed
  

  # Example Pod dependency
  pod 'Firebase/Analytics'

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Disable Bitcode as per your existing configuration
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '5.5'
      # Exclude i386 and arm64e architectures based on the supported architectures
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386 arm64e'
      
      # Define module
      config.build_settings['DEFINES_MODULE'] = 'YES'

      # Ensure base configuration is set to nil to avoid custom settings conflicts
      config.base_configuration_reference = nil
    end
  end
end
