name: Build and Release iOS IPA

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: Build iOS IPA
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          
      - name: Add `build_runner` Package
        run: dart pub add dev:build_runner    

      - name: Install Dependencies
        run: flutter pub get

      - name: Ensure CocoaPods is up-to-date
        run: pod repo update
        working-directory: ios

      - name: Install CocoaPods dependencies
        run: |
          pod install --repo-update
        working-directory: ios

      - name: Clean Flutter Project
        run: flutter clean

      - name: Regenerate `GeneratedPluginRegistrant.m` and Dependencies
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build iOS IPA
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -configuration Release \
                     -archivePath build/ios/archive/Runner.xcarchive \
                     archive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
                     -archivePath build/ios/archive/Runner.xcarchive \
                     -exportPath build/ios/iphoneos \
                     -exportOptionsPlist ios/exportOptions.plist

      - name: Upload IPA to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.PAT_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "Congrats on successfully building the iOS IPA!"
