name: Build and Release iOS Ipa

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: Build iOS Ipa
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Install Dependencies
        run: flutter pub get -v

      - name: Clean old Pods, Podfile.lock, and Derived Data
        run: |
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf ~/Library/Developer/Xcode/DerivedData
          flutter clean  # Clean Flutter's build cache
          flutter pub get  # Re-fetch dependencies

      - name: Ensure CocoaPods is up-to-date
        run: pod repo update
        working-directory: ios

      - name: Install CocoaPods dependencies
        run: |
          pod install --verbose
          pod repo update  # Update the CocoaPods repo to ensure latest versions are fetched
        working-directory: ios

      - name: Regenerate `GeneratedPluginRegistrant.m`
        run: |
          flutter pub get
          flutter clean
          flutter pub run build_runner build  # Force regeneration of the `GeneratedPluginRegistrant.m`

      - name: Build iOS IPA
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -configuration Release \
                     -archivePath build/ios/archive/Runner.xcarchive \
                     archive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
                     -archivePath build/ios/archive/Runner.xcarchive \
                     -exportPath build/ios/iphoneos \
                     -exportOptionsPlist ios/exportOptions.plist

      - name: Upload IPA to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.PAT_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "Congrats on successfully building the iOS IPA!"
